fix: filter deleted IAM principals
If an existing IAM policy contains a deleted principal for a non-authoritative role this results
in an error, as terraform does not support IAM policies for deleted principals:

Error: invalid value for binding.X.members.X

To avoid this error we filter out any kind of deleted principal in the resulting final map used to
build the IAM policy.